products = [
    {
        '_id': '1',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/static/images/airpods.jpg',
        'description':
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'iPhone 11 Pro 256GB Memory',
        'image': '/static/images/phone.webp',
        'description':
        'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 599.99,
        'countInStock': 0,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Cannon EOS 80D DSLR Camera',
        'image': '/static/images/camera.webp',
        'description':
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
        'brand': 'Cannon',
        'category': 'Electronics',
        'price': 929.99,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Sony Playstation 4 Pro White Version',
        'image': '/static/images/playstation.webp',
        'description':
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
        'brand': 'Sony',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Logitech G-Series Gaming Mouse',
        'image': '/static/images/mouse.jpg',
        'description':
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
        'brand': 'Logitech',
        'category': 'Electronics',
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Amazon Echo Dot 3rd Generation',
        'image': '/static/images/alexa.jpg',
        'description':
        'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'Samsung Galaxy Watch 4',
        'image': '/static/images/watch.jpg',
        'description': 'Track your fitness progress with our first smartwatch that conveniently measures body composition.',
        'brand': 'Samsung',
        'category': 'Electronics',
        'price': 199.99,
        'countInStock': 15,
        'rating': 4.5,
        'numReviews': 20,
    },
    {
        '_id': '8',
        'name': 'MacBook Pro 14-inch',
        'image': '/static/images/macbook.jpg',
        'description': 'The most powerful MacBook Pro ever is here. With the blazing-fast M1 Pro or M1 Max chip.',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 1999.99,
        'countInStock': 5,
        'rating': 5.0,
        'numReviews': 15,
    },
    {
        '_id': '9',
        'name': 'Bose QuietComfort 45',
        'image': '/static/images/bose.jpg',
        'description': 'The first noise cancelling headphones are back, with world-class quiet, lightweight materials.',
        'brand': 'Bose',
        'category': 'Electronics',
        'price': 329.00,
        'countInStock': 12,
        'rating': 4.5,
        'numReviews': 18,
    },
    {
        '_id': '10',
        'name': 'Nintendo Switch OLED Model',
        'image': '/static/images/switch.jpg',
        'description': 'Enjoy vibrant colors and crisp contrast with a screen that makes colors pop.',
        'brand': 'Nintendo',
        'category': 'Electronics',
        'price': 349.99,
        'countInStock': 8,
        'rating': 4.8,
        'numReviews': 30,
    },
    {
        '_id': '11',
        'name': 'iPad Air 5th Generation',
        'image': '/static/images/ipad.jpg',
        'description': 'With the breakthrough M1 chip, iPad Air is a creative and gaming powerhouse.',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 599.00,
        'countInStock': 20,
        'rating': 4.7,
        'numReviews': 22,
    },
    {
        '_id': '12',
        'name': 'Dell XPS 13 Laptop',
        'image': '/static/images/dell.jpg',
        'description': 'Stunning 4-sided InfinityEdge display allows us to bring a 6.8% larger 16:10 display to the 13-inch.',
        'brand': 'Dell',
        'category': 'Electronics',
        'price': 1249.99,
        'countInStock': 6,
        'rating': 4.2,
        'numReviews': 11,
    },
    {
        '_id': '13',
        'name': 'GoPro HERO10 Black',
        'image': '/static/images/gopro.jpg',
        'description': 'All-out speed and ultimate ease, now in the most powerful GoPro ever.',
        'brand': 'GoPro',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 14,
        'rating': 4.6,
        'numReviews': 25,
    },
    {
        '_id': '14',
        'name': 'Kindle Paperwhite 11th Gen',
        'image': '/static/images/kindle.jpg',
        'description': 'Now with a 6.8 display and thinner borders, adjustable warm light, and up to 10 weeks of battery life.',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 139.99,
        'countInStock': 25,
        'rating': 4.8,
        'numReviews': 40,
    },
    {
        '_id': '15',
        'name': 'Dyson V15 Detect Vacuum',
        'image': '/static/images/dyson.jpg',
        'description': 'The most powerful, intelligent cordless vacuum. Lasers reveal microscopic dust.',
        'brand': 'Dyson',
        'category': 'Home Appliances',
        'price': 749.99,
        'countInStock': 4,
        'rating': 4.9,
        'numReviews': 9,
    },
    {
        '_id': '16',
        'name': 'Samsung 55-inch QLED 4K TV',
        'image': '/static/images/tv.jpg',
        'description': 'Experience 100% Color Volume with Quantum Dot technology for billion shades of color.',
        'brand': 'Samsung',
        'category': 'Electronics',
        'price': 897.99,
        'countInStock': 3,
        'rating': 4.4,
        'numReviews': 14,
    },
    {
        '_id': '17',
        'name': 'Razer BlackWidow V3 Keyboard',
        'image': '/static/images/keyboard.jpg',
        'description': 'The name that started it all returns to reassert its dominance with mechanical switches.',
        'brand': 'Razer',
        'category': 'Electronics',
        'price': 139.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 16,
    },
    {
        '_id': '18',
        'name': 'Microsoft Surface Laptop 4',
        'image': '/static/images/surface.jpg',
        'description': 'Performance for multitasking, video chats, and entertainment. Slim and sleek design.',
        'brand': 'Microsoft',
        'category': 'Electronics',
        'price': 999.00,
        'countInStock': 7,
        'rating': 4.3,
        'numReviews': 13,
    },
    {
        '_id': '19',
        'name': 'Beats Studio3 Wireless',
        'image': '/static/images/beats.jpg',
        'description': 'Pure Adaptive Noise Cancelling (Pure ANC) actively blocks external noise.',
        'brand': 'Beats',
        'category': 'Electronics',
        'price': 349.95,
        'countInStock': 11,
        'rating': 4.2,
        'numReviews': 21,
    },
    {
        '_id': '20',
        'name': 'Fujifilm Instax Mini 11',
        'image': '/static/images/instax.jpg',
        'description': 'Live Life and Play. Instant photos with automatic exposure and selfie mode.',
        'brand': 'Fujifilm',
        'category': 'Electronics',
        'price': 79.95,
        'countInStock': 18,
        'rating': 4.7,
        'numReviews': 35,
    },
    {
        '_id': '21',
        'name': 'SteelSeries Arctis 7 Headset',
        'image': '/static/images/steelseries.jpg',
        'description': 'Lossless 2.4 GHz wireless audio designed for low latency gaming.',
        'brand': 'SteelSeries',
        'category': 'Electronics',
        'price': 169.99,
        'countInStock': 9,
        'rating': 4.6,
        'numReviews': 28,
    },
    {
        '_id': '22',
        'name': 'Google Pixel 6 Pro',
        'image': '/static/images/pixel.jpg',
        'description': 'The smartest and fastest Pixel yet. Fully loaded with an advanced camera system.',
        'brand': 'Google',
        'category': 'Electronics',
        'price': 899.00,
        'countInStock': 0,
        'rating': 4.1,
        'numReviews': 19,
    },
    {
        '_id': '23',
        'name': 'ASUS ROG Swift Monitor',
        'image': '/static/images/monitor.jpg',
        'description': '27-inch 4K UHD gaming monitor with an overclockable 144Hz refresh rate.',
        'brand': 'ASUS',
        'category': 'Electronics',
        'price': 699.00,
        'countInStock': 4,
        'rating': 4.8,
        'numReviews': 10,
    },
    {
        '_id': '24',
        'name': 'Corsair Vengeance LPX 16GB',
        'image': '/static/images/ram.jpg',
        'description': 'Designed for high-performance overclocking. Heat spreader made of pure aluminum.',
        'brand': 'Corsair',
        'category': 'Electronics',
        'price': 74.99,
        'countInStock': 30,
        'rating': 4.9,
        'numReviews': 50,
    },
    {
        '_id': '25',
        'name': 'WD Black 1TB NVMe SSD',
        'image': '/static/images/ssd.jpg',
        'description': 'Next-gen PCIe Gen4 technology optimized for top-tier gaming.',
        'brand': 'WD',
        'category': 'Electronics',
        'price': 129.99,
        'countInStock': 22,
        'rating': 4.9,
        'numReviews': 45,
    },
    {
        '_id': '26',
        'name': 'Blue Yeti USB Microphone',
        'image': '/static/images/yeti.jpg',
        'description': 'Create unparalleled recordings with your computer using Blue Best-selling Yeti family.',
        'brand': 'Blue',
        'category': 'Electronics',
        'price': 129.00,
        'countInStock': 13,
        'rating': 4.6,
        'numReviews': 60,
    },
    {
        '_id': '27',
        'name': 'TP-Link WiFi 6 Router',
        'image': '/static/images/router.jpg',
        'description': 'Next-gen 1.8 Gbps speeds. Enjoy smoother streaming, gaming, and downloading.',
        'brand': 'TP-Link',
        'category': 'Electronics',
        'price': 99.99,
        'countInStock': 16,
        'rating': 4.4,
        'numReviews': 24,
    },
    {
        '_id': '28',
        'name': 'Anker PowerCore 26800',
        'image': '/static/images/powerbank.jpg',
        'description': 'Colossal capacity portable charger with dual input port and high-speed charging.',
        'brand': 'Anker',
        'category': 'Electronics',
        'price': 65.99,
        'countInStock': 40,
        'rating': 4.8,
        'numReviews': 100,
    },
    {
        '_id': '29',
        'name': 'Fitbit Charge 5',
        'image': '/static/images/fitbit.jpg',
        'description': 'Advanced fitness and health tracker with built-in GPS, stress management tools.',
        'brand': 'Fitbit',
        'category': 'Electronics',
        'price': 149.95,
        'countInStock': 14,
        'rating': 4.3,
        'numReviews': 32,
    },
    {
        '_id': '30',
        'name': 'JBL Flip 6 Speaker',
        'image': '/static/images/jbl.jpg',
        'description': 'Eco-friendly packaging. IP67 waterproof and dustproof. 12 hours of playtime.',
        'brand': 'JBL',
        'category': 'Electronics',
        'price': 129.95,
        'countInStock': 20,
        'rating': 4.7,
        'numReviews': 44,
    },
]
